#pragma once
#include <QApplication>
#include <QClipboard>
#include <QDir>
#include <QFileDialog>
#include <QColorSpace>
#include <QImageWriter>
#include <QLabel>
#include <QMenuBar>
#include <QMessageBox>
#include <QMimeData>
#include <QPainter>
#include <QScreen>
#include <QStandardPaths>
#include <QStatusBar>
#include <QtWidgets/QStackedWidget>
#include <QGroupBox>
#include <QPushButton>
#include <QImageReader>
#include <QCheckBox>
#include <QGridLayout>
#include <qlineedit.h>

